- name: "Setup Nucypher"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: Recursively change ownership of geth directory
      become: yes
      file:
        path: /home/nucypher/geth
        state: directory
        recurse: yes
        owner: nucypher

    - name: Stop any running Ursulas
      become: yes
      become_user: nucypher
      docker_container:
        name: ursula
        state: stopped
        image: "{{ docker_image | default('nucypher/nucypher:latest') }}"
      ignore_errors: yes

    - name: Keep disk space clean by pruning unneeded docker debris
      become: yes
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes

    - name: "pull {{ docker_image | default('nucypher/nucypher:latest') }}"
      become: yes
      docker_image:
        name: "{{ docker_image | default('nucypher/nucypher:latest') }}"
        source: pull
        force_source: yes

    - name: "check if /home/nucypher/nucypher/ursula.json exists"
      become: yes
      become_user: nucypher
      stat:
        path: /home/nucypher/nucypher/ursula.json
      register: ursula_check

    - name: find keystore file
      find:
        paths: "{{geth_dir}}keystore"
      register: keystore_output

    - name: store signer options
      set_fact:
        signer_options: "--signer keystore://{{nucypher_container_geth_datadir}}/keystore/{{keystore_output.files[0].path | basename}}"
      when: ursula_check.stat.exists == False

    - name: Find my public ip
      uri:
        url: https://api.ipify.org
        return_content: yes
      register: ip_response

    - name: "init Ursula operator"
      become: yes
      become_user: nucypher
      when: ursula_check.stat.exists == False
      command: "docker run -v /home/nucypher:/root/.local/share/ \
        -e NUCYPHER_KEYSTORE_PASSWORD -it {{ docker_image | default('nucypher/nucypher:latest') }} \
        nucypher ursula init \
        --key-material {{keymaterial}} \
        --eth-endpoint {{ eth_endpoint }} \
        --operator-address {{active_account.stdout}} \
        --rest-host {{ip_response.content}} \
        --domain {{network_name}} \
        --polygon-endpoint {{polygon_endpoint}} \
        {{nucypher_ursula_init_options | default('')}} {{signer_options}}"
      environment:
        NUCYPHER_KEYSTORE_PASSWORD: "{{runtime_envvars['NUCYPHER_KEYSTORE_PASSWORD']}}"
